/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qqNXkdUqQOB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useRouter } from 'next/navigation';
import { useState, useEffect } from 'react';
export function ChatuiPage() {
  const router = useRouter();




  return (
    (<div
      className="flex flex-col h-screen bg-gradient-to-br from-[#55efc4] to-[#ffeaa7]">
      <header
        className="flex items-center justify-between h-16 px-4 bg-[#00b894] text-black">
        <div className="flex items-center gap-2">
          <div
            className="rounded-full w-8 h-8 bg-[#fdcb6e] text-3xl flex items-center justify-center">🤖</div>
          <h1 className="text-lg font-bold">ChatAI</h1>
        </div>
        <div
          className="rounded-full w-10 h-10 bg-[#55efc4] text-3xl flex items-center justify-center">😊</div>
      </header>
      <div className="flex-1 overflow-y-auto p-4 text-black">
        <div className="flex items-start gap-4 mb-4">
          <div
            className="rounded-full w-10 h-10 bg-[#fdcb6e] text-3xl flex items-center justify-center">🤖</div>
          <div className="bg-white rounded-3xl p-3 max-w-[70%] relative">
            <p>Hi there! I'm your friendly AI assistant. How can I help you today?</p>
            <div
              className="absolute bottom-0 left-1/2 transform -translate-x-1/2 -translate-y-1/2 flex gap-2">


            </div>
          </div>
        </div>
        <div className="flex items-start gap-4 mb-4 justify-end">
          <div className="bg-[#55efc4] rounded-3xl p-3 max-w-[70%] relative">
            <p>Hello! I'm doing great, thanks for asking. I'm always happy to chat and help out however I can.</p>
            <div
              className="absolute bottom-0 left-1/2 transform -translate-x-1/2 -translate-y-1/2 flex gap-2">

            </div>
          </div>
          <div
            className="rounded-full w-10 h-10 bg-[#fd79a8] text-3xl flex items-center justify-center">😊</div>
        </div>
        <div className="flex items-start gap-4 mb-4">
          <div
            className="rounded-full w-10 h-10 bg-[#55efc4] text-3xl flex items-center justify-center">🤖</div>
          <div className="bg-[#ffeaa7] rounded-3xl p-3 max-w-[70%] relative">
            <p>
              That's great to hear! I'm always excited to learn new things. Do you have any fun hobbies or interests
              you'd like to share?
            </p>
            <div
              className="absolute bottom-0 left-1/2 transform -translate-x-1/2 -translate-y-1/2 flex gap-2">


            </div>
          </div>
        </div>
      </div>
      <div className="bg-[#00b894] p-4 flex items-center gap-2">
        <Input
          type="text"
          placeholder="Type your message..."
          className="bg-white rounded-full px-4 py-2 flex-1" />
        <Button variant="ghost" className="rounded-full text-white">
          <SendIcon className="w-6 h-6" />
        </Button>
      </div>
    </div>)
  );
}

function SendIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>)
  );
}
