/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qqNXkdUqQOB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import { useRouter, useSearchParams } from 'next/navigation';
import { useState, useEffect } from 'react';
import { fetchAccessToken } from "@humeai/voice";
import { VoiceProvider, useVoice } from "@humeai/voice-react";
import ClientComponent from "@/components/client-component";

export function ChatuiPage() {
    const router = useRouter();
    const searchParams = useSearchParams();
    const [prompt, setPrompt] = useState('');
    const [module, setModule] = useState('');

    useEffect(() => {
        const promptParam = searchParams.get('prompt');
        const moduleParam = searchParams.get('module');
        if (promptParam) {
            setPrompt(promptParam);
        }
        if (moduleParam) {
            setModule(moduleParam);
        }
    }, [searchParams]);

    return (
        <div className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 text-black p-4">
            <ClientComponent prompt={ prompt } module={ module }/>
        </div>
    );
}
