/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BmnIJvPVXvv
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Manrope } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

manrope({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"
import { useRouter } from 'next/navigation';

export function Lessonpage() {
    const router = useRouter();
  const [score, setScore] = useState(0)
  const [currentProblem, setCurrentProblem] = useState({
    a: getRandomInt(1, 5),
    b: getRandomInt(1, 5),
  })
  function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }
  function generateNewProblem() {
    setCurrentProblem({
      a: getRandomInt(1, 5),
      b: getRandomInt(1, 5),
    })
  }
  function handleAnswer(answer) {
    const result = currentProblem.a + currentProblem.b
    if (answer === result) {
      setScore(score + 1)
      generateNewProblem()
    } else {
    }
  }
  return (
    (<div
      className="flex flex-col items-center justify-center min-h-screen bg-[#FFF7EC] text-[#FF9800]">
      <div className="flex items-center gap-4 mb-8">
        <SmileIcon className="w-12 h-12" />
        <h1 className="text-4xl font-bold">Let&apos;s Add!</h1>
      </div>
      <div
        className="flex flex-col items-center gap-4 p-8 rounded-xl bg-white shadow-lg">
        <div className="flex gap-4 items-center">
          <div className="grid grid-cols-[repeat(currentProblem.a,1fr)] gap-2">
            {Array.from({ length: currentProblem.a }).map((_, i) => (
              <AppleIcon key={i} className="w-8 h-8" />
            ))}
          </div>
          <PlusIcon className="w-8 h-8" />
          <div className="grid grid-cols-[repeat(currentProblem.b,1fr)] gap-2">
            {Array.from({ length: currentProblem.b }).map((_, i) => (
              <AppleIcon key={i} className="w-8 h-8" />
            ))}
          </div>
        </div>
        <div className="flex gap-4">
          {Array.from({ length: 10 }).map((_, i) => (
            <Button
              key={i}
              variant="ghost"
              size="lg"
              onClick={() => handleAnswer(i)}
              className="w-12 h-12 rounded-full bg-[#FFF7EC] text-[#FF9800] font-bold">
              {i}
            </Button>
          ))}
        </div>
      </div>
      <div className="flex items-center gap-4 mt-8">
        <div className="flex items-center gap-2">
          <StarIcon className="w-6 h-6" />
          <span className="text-2xl font-bold">{score}</span>
        </div>
        <Progress value={score * 10} className="w-64 h-6 rounded-full" />
      </div>
    </div>)
  );
}

function AppleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
      <path d="M10 2c1 .5 2 2 2 5" />
    </svg>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}


function SmileIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M8 14s1.5 2 4 2 4-2 4-2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>)
  );
}


function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}
